services:
  vsserver:
    image: ghcr.io/asterle/vintagestory:latest
    container_name: vsserver
    restart: unless-stopped
    volumes:
      # • your world will be in /appdata/vintagestory/vs by default (/gamedata/vs on the container)
      # • if you run multiple servers just change the left part
      # • you could also use docker volumes instead of host path
      - /.vsdata:/gamedata
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    environment:
      VS_DATA_PATH: /gamedata